typography_spectrum: 0.6700399422552437
color:
  brandColors: []
  brandStrength: 0.7580302637070417
  lightness: 0.6390841389074922
  saturation: 0.7846366497687995
  rhythmicContrast: 0.13249820843338966
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8682124889455736
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Michael Day
  email: michaelgday@gmail.com
name: Michael Day
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
